name: Daily AI Tools Update
on:
  schedule:
    - cron: '0 4 * * *' # Runs at 4 AM UTC daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests
      - name: Run Scraper
        run: python update_ai_tools.py
      - name: Commit and Push
        run: |
          git config --global user.name "AI Update Bot"
          git config --global user.email "bot@github.com"
          git add ai-tools.json
          git commit -m "chore: automated daily update $(date +'%Y-%m-%d')" || exit 0
          git push
